name: linting

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
jobs:
    lint-and-build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v2
        - run: bun install
        - run: bun run lint
        - run: bun run build
        - uses: vale-cli/vale-action@v2
          with:
            files: "src/content"
            fail_on_error: "true"
            reporter: "github-check"
